//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceVPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laptopEntities : DbContext
    {
        public laptopEntities()
            : base("name=laptopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<chitietgiohang> chitietgiohang { get; set; }
        public virtual DbSet<chitiethoadon> chitiethoadon { get; set; }
        public virtual DbSet<giohang> giohang { get; set; }
        public virtual DbSet<hang> hang { get; set; }
        public virtual DbSet<hoadon> hoadon { get; set; }
        public virtual DbSet<sanpham> sanpham { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
