//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceVPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitietgiohang = new HashSet<chitietgiohang>();
            this.chitiethoadon = new HashSet<chitiethoadon>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string CPU { get; set; }
        public string Ram { get; set; }
        public string OCung { get; set; }
        public string ManHinh { get; set; }
        public string VGA { get; set; }
        public string HeDieuHanh { get; set; }
        public string TrongLuong { get; set; }
        public string Pin { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietgiohang> chitietgiohang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadon { get; set; }
        public virtual hang hang { get; set; }
    }
}
